name: linter

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: add conda to system path
        #checks if conda is installed before installing again
        run: |
          if ! test -f ~/miniconda3/bin/conda; then
            mkdir -p ~/miniconda3
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
            bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
            rm -rf ~/miniconda3/miniconda.sh
            ~/miniconda3/bin/conda init bash
            rm -rf ~/.condarc
            ~/miniconda3/bin/conda update conda
          fi

      - name: Install dependencies
        # creates a new conda environment
        run: |
          if test -d ~/miniconda3/envs/intrusionDetectionSystem; then
            conda remove -y -n intrusionDetectionSystem --all
            rm -rf ~/miniconda3/envs/intrusionDetectionSystem
          fi
          conda env create --file=env.yml

      - name: Lint with flake8
        run: |
          pip install -y flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-line-length=127 --statistics
